#!/usr/bin/env python3
"""
cleanup_capstone.py

Deletes automatically generated files based ONLY on file extension.
Keeps all .fit/.fits science images safe.

Removes:
 - .txt     (extracted 1D spectra)
 - .png     (output plots from streak/first order/gradient)
 - .reg     (DS9 line projection files)
 - .csv     (summary reports)
"""

import os
from pathlib import Path

# Extensions to remove
EXTENSIONS_TO_DELETE = {
    ".txt",
    ".png",
    ".reg",
    ".csv"
}

def clean_directory(directory="."):
    directory = Path(directory)
    removed = 0

    print("\nCleaning autogenerated files by extension...\n")

    for file in directory.iterdir():
        if not file.is_file():
            continue

        ext = file.suffix.lower()

        # Skip FITS files
        if ext in {".fits", ".fit"}:
            continue

        if ext in EXTENSIONS_TO_DELETE:
            try:
                file.unlink()
                print(f"Removed: {file}")
                removed += 1
            except Exception as e:
                print(f"Failed to delete {file}: {e}")

    print(f"\nFinished. Total deleted: {removed}\n")


def main():
    clean_directory(".")


if __name__ == "__main__":
    main()
